services:
  - type: web
    name: rifa-fegsat
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SHEET_ID
        value: 1vvyEHc12FvAKpzMY0a47FgHnYKAl2itGyU1fxPBM1Jc
      - key: ADMIN_PASSWORD
        value: fegsat2026
      - key: PORT
        value: 5000
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        fromGroup: rifa-secrets
